<?php

return [

    'mapping' => [
    	'mp9' => 'A',
		'nova' => 'B',
		'p90' => 'C',
		'scar20' => 'D',
		'sg556' => 'E',
		'scout' => 'F',
		'ct-knife' => 'G',
		'flashbang' => 'H',
		'grenade' => 'I',
		'smoke' => 'J',
		'molotov' => 'K',
		'decoy' => 'L',
		'incendiary' => 'M',
		'c4' => 'N',
		'tr-knife' => 'O',
		'knife' => 'O',
		'usps' => 'P',
		'cz75a' => 'Q',
		'revolver' => 'R',
		'kevlar' => 'S',
		'helmet' => 'T',
		'defuse' => 'U',
		'bayonet' => 'V',
		'flip' => 'W',
		'gut' => 'X',
		'karambit' => 'Y',
		'm9' => 'Z',
		'deagle' => 'a',
		'dualies' => 'b',
		'fiveseven' => 'c',
		'glock' => 'd',
		'ak47' => 'e',
		'aug' => 'f',
		'awp' => 'g',
		'famas' => 'h',
		'm249' => 'i',
		'g3sg1' => 'j',
		'galilar' => 'k',
		'm4a1' => 'l',
		'm4a1silencer' => 'm',
		'mac10' => 'n',
		'p2000' => 'o',
		'mp5' => 'p',
		'ump' => 'q',
		'xm1014' => 'r',
		'bizon' => 's',
		'mag7' => 't',
		'negev' => 'u',
		'sawedoff' => 'v',
		'tek9' => 'w',
		'taser' => 'x',
		'p250' => 'y',
		'mp7' => 'z',
    ],

];
